repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Git state
      - id: check-merge-conflict
        stages: [commit]
      # Sensitive information
      - id: detect-private-key
        stages: [commit]
      # Generic file state
      - id: trailing-whitespace
        stages: [commit]
      - id: mixed-line-ending
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
      # Language syntax/formatting
      - id: check-yaml
        stages: [commit]
  - repo: local
    hooks:
      - id: rubocop
        name: Check Ruby style with rubocop
        entry: .hooks/rubocop.sh
        language: script
        types: ['ruby']
        stages: [ commit ]
